replicaCount: 2

# Environment variables for the application
env:
  SERVICE_NAME: "redis-gateway"
  SENTINEL_ADDR: "redis-sentinel-server:26379"
  MASTER_NAME: "mymaster"
  LEASE_NAME: "redis-gateway-lease"
  POLL_INTERVAL: "5s"  # Poll interval for checking Redis Sentinel changes
  TICK_INTERVAL: "1s"  # Interval for checking if an update needs to be applied
  REDIS_PASSWORD_SECRET_NAME: "redis-sentinel-server"  # Default secret name for Redis password
  REDIS_PASSWORD_KEY: "redis-password"  # Default key in the secret for Redis password
  REDIS_PASSWORD: ""  # Direct Redis password (if not using a secret)

# Resource requests and limits for the container
resources:
  requests:
    cpu: "10m"
    memory: "10Mi"
  limits:
    cpu: "50m"
    memory: "50Mi"

# Labels for the pods
podlabels: {}
# Annotations for the pods
podAnnotations: {}

# Node selector for scheduling the pods on specific nodes
nodeSelector: {}
  # Services: redis

# Tolerations for the pods
tolerations: []
# - key: "name"
#   effect: "NoSchedule"

# Image configuration
image:
  repository: "promzeus/redis-sentinel-gateway"
  tag: "v1"
  pullPolicy: "Always"

# Service account name
serviceAccount:
  create: ture